GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiR2luYSIsImlhdCI6MTY1NTI5MzQ2NCwiZXhwIjoxNjU1MjkzNDk0fQ.h6hnOFwA89WpU2g5i7TeUKBdxwZQdXYk2wCOdH0uJxw

###

POST http://localhost:4000/login
//if it s a post, I need to prepare a content type
Content-Type: application/json

{
    "username": "Gina"
}

### 

POST http://localhost:4000/token
Content-Type: application/json
{
    "token": ""
}
